### Recursive Route Planner ###

You've been selected for an internship at TomTom and as a part of your first project, you have been asked to design the core functionality for a route planner that computes the path between two points in a city. TomTom stores top-down 2D views of a city in a 2D Numpy array. An example layout for a city is shown below:

```python
city_map = np.array([[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 0, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 0, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 0, 1, 1, 1, 1 ],
[ 1, 0, 1, 1, 1, 1, 1, 1, 0, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 0, 1, 1, 1, 1, 0, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 ]]
)
```

In this map, locations marked with ‘1’ represents empty-spaces whereas ‘0’ represent buildings. Your task is to code a solution that computes a driving route via empty spaces from one end of the city to the other subject to the following constraints:

1. Drivers always start from an empty-space in the extreme left column (```city_map[:,0]```) and always terminate their journey in the column on the extreme right (```city_map[:,-1]```).

2. They never revisit a location they’ve already passed.

3. Drivers do not move diagonally.

4. Locations directly above, below, left and right of a building are their designated parking spots. Drivers cannot drive through these locations (they cannot be used for the path).

5. Drivers are not concerned about the distance. All valid paths are admissible as a solution irrespective of their length.

To get started, follow these steps:

1. Given a city map, mark locations directly above, below, left and right of a building as blocked (remember, they are parking locations for the building and cannot be used for the route). Save this transformed map in a second map called
```marked_city_map```.

2. Once you have a ```marked_city_map```, you will start from a location in the left-most column. Before moving into a new location, you must check if it is blocked (note that you cannot stand at a location of a building or parking). Once you move into an unblocked spot, you can then look again in four possible directions (up, down, left, right) to see if you can move there.

3. You must implement the above procedure using a **recursive** function that takes a step in all unblocked directions and checks if it can then repeat this again. It recursively repeats this till it reaches the final column.

You can break this into the following functions:

1. [1 point] Write a function ```mark_parking_locations()``` takes a 2D Numpy array ```city_map``` as an argument and converts it to a ```marked_city_map``` by marking all parking locations. You should mark parking locations with -1 in your Numpy array.

```python
def mark_parking_locations(city_map):
    ...
    return marked_city_map
```

For the ```city_map``` given above, you should obtain the following ```marked_city_map```. 

```python
array([[ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1,  0, -1, -1,  1,  1,  1,  1,  1,  1],
       [ 1, -1, -1,  0, -1,  1,  1,  1,  1,  1],
       [ 1,  1,  1, -1,  0, -1,  1,  1,  1,  1],
       [ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1],
       [ 1, -1,  1,  1, -1,  0, -1,  1, -1,  1],
       [-1,  0, -1,  1,  1, -1,  1, -1,  0, -1],
       [ 1, -1,  1,  1,  1,  1,  1,  1, -1,  1],
       [-1,  1,  1,  1,  1, -1,  1,  1,  1,  1],
       [ 0, -1,  1,  1, -1,  0, -1,  1,  1,  1],
       [-1,  1,  1, -1,  1, -1,  1,  1,  1,  1],
       [ 1,  1, -1,  0, -1,  1,  1,  1,  1,  1]])
```
2. [3 points] The function ```find_route()``` _recursively_ computes the path from a starting location in the first column (given by coordinates (0,y)) to **any** location in the final column. During the search process, it must mark the moves already made on the map. You can use numbers like ```{10, 20, 30, 40}``` as direction codes for the four directions ```{UP, DOWN, LEFT, RIGHT}``` directions. The prototype for this function is given below.

```python
def find_route(route_map, current_loc, visited_locs):
    ...
```

Your recursive function MUST use the following arguments

- route_map: A map marked with direction codes for a specific route.
- current_loc: Tuple containing the current location on the map.
- visited_locs: A list of tuples containing previously visited locations.

In addition to these mandatory arguments, you may optionally use additional arguments if necessary. The function returns a completed route map map marked with direction codes for a valid route. If no valid route can be found, return ```None```. An example output from this function is provided below:

```python
array([[ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1,  0, -1, -1,  1,  1,  1,  1,  1,  1],
       [20, -1, -1,  0, -1,  1,  1,  1,  1,  1],
       [40, 40, 20, -1,  0, -1,  1,  1,  1,  1],
       [ 1,  1, 20,  1, -1, -1,  1,  1,  1,  1],
       [ 1, -1, 40, 20, -1,  0, -1,  1, -1,  1],
       [-1,  0, -1, 20,  1, -1,  1, -1,  0, -1],
       [ 1, -1, 20, 30, 40, 40, 40, 20, -1,  1],
       [-1,  1, 20, 40, 10, -1,  1, 40, 40,  1],
       [ 0, -1, 40, 10, -1,  0, -1,  1,  1,  1],
       [-1,  1,  1, -1,  1, -1,  1,  1,  1,  1],
       [ 1,  1, -1,  0, -1,  1,  1,  1,  1,  1]])
```

3. [1 point] Finally, you should create a ```pretty_printer()``` function to show a readable output to the user. Python’s support for the Unicode specification for representing textual data allows you to create something like the example shown below. You can use different symbols if you prefer as long as it is meaningful. For this, replace the codes for building, parking spaces and direction codes ```{UP, DOWN, LEFT, RIGHT}``` with their corresponding symbols.

```python
def pretty_printer(route_map):
    ...
    return None
```

An example output:

```python
['🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['❌', '🏢', '❌', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['⬇️', '❌', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['➡️', '➡️', '⬇️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '🛣️', '⬇️', '🛣️', '❌', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '❌', '➡️', '⬇️', '❌', '🏢', '❌', '🛣️', '❌', '🛣️']
['❌', '🏢', '❌', '⬇️', '🛣️', '❌', '🛣️', '❌', '🏢', '❌']
['🛣️', '❌', '⬇️', '⬅️', '➡️', '➡️', '➡️', '⬇️', '❌', '🛣️']
['❌', '🛣️', '⬇️', '➡️', '⬆️', '❌', '🛣️', '➡️', '➡️', '🛣️']
['🏢', '❌', '➡️', '⬆️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️']
['❌', '🛣️', '🛣️', '❌', '🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '🛣️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
```


For this exercise, you are free to use as many ancillary user-defined functions as you need.



In [5]:
# We will first import numpy as we will use it to write our fuctions. 
import numpy as np

# We define an example city map, as given in the problem explanation. We will use it to check if our functions work. 
city_map = np.array([[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 0, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 0, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 0, 1, 1, 1, 1 ],
[ 1, 0, 1, 1, 1, 1, 1, 1, 0, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 0, 1, 1, 1, 1, 0, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 ]]
)

----------

For the first function, we start with creating a copy of the argument to manipulate it and return it. We call it as `marked_city_map`. Then, we create a loop for every row of our list, city map. For each row, we create another loop to iterate over the each index element (column) of the row. Later, we initiate a conditional statement to find a building. Inside this conditional statement, we nest several other conditional statements to ensure we are not trying to access a row or column that doesn't exist or out of bounds. Finally, we mark the cell directly above, below, left, and right of the current building as -1, and return the output.

In [7]:
def mark_parking_locations(city_map):
    """
    Marks parking locations around buildings in a city map.

    In the provided city_map (2D NumPy array), locations marked with '0' represent buildings. This function marks the locations 
    directly adjacent (up, down, left, right) to each building as blocked (using -1) in the returned marked_city_map.

    Args:
    city_map (np.ndarray): A 2D NumPy array representing the city layout, where '1' indicates empty space and '0' indicates a building.

    Returns:
    np.ndarray: A new 2D NumPy array (marked_city_map) where all parking locations are marked with -1.
    """
    
    # We create a copy of the original city map 
    marked_city_map = np.copy(city_map)

    # We iterate over each row in the city_map
    for row in range(len(city_map)):
        # We iterate over each column in the current row
        for col in range(len(city_map[row])):
            
            # We check if the current location is a building
            if city_map[row][col] == 0:  
                # We mark the location above as blocked if it exists
                if row > 0:  # Up
                    marked_city_map[row - 1][col] = -1 
                # We mark the location below as blocked if it exists
                if row < len(city_map) - 1:  # Down
                    marked_city_map[row + 1][col] = -1 
                # We mark the location to the left as blocked if it exists
                if col > 0:  # Left
                    marked_city_map[row][col - 1] = -1 
                # We mark the location to the right as blocked if it exists
                if col < len(city_map[0]) - 1:  # Right
                    marked_city_map[row][col + 1] = -1 
    
    return marked_city_map

In [8]:
# Now let's check if the function behaves as we intended so, by printing the output. 

route_map = mark_parking_locations(city_map)
print(route_map)

[[ 1 -1  1  1  1  1  1  1  1  1]
 [-1  0 -1 -1  1  1  1  1  1  1]
 [ 1 -1 -1  0 -1  1  1  1  1  1]
 [ 1  1  1 -1  0 -1  1  1  1  1]
 [ 1  1  1  1 -1 -1  1  1  1  1]
 [ 1 -1  1  1 -1  0 -1  1 -1  1]
 [-1  0 -1  1  1 -1  1 -1  0 -1]
 [ 1 -1  1  1  1  1  1  1 -1  1]
 [-1  1  1  1  1 -1  1  1  1  1]
 [ 0 -1  1  1 -1  0 -1  1  1  1]
 [-1  1  1 -1  1 -1  1  1  1  1]
 [ 1  1 -1  0 -1  1  1  1  1  1]]


---------

For the second function, we use three arguments: `route_map`, `current_loc`, and `visited_locs`. We unpack current location tuple to enable manipulation of a specific position, and store it as `current_loc`. Then, through the .shape, we return a tuple that contains the the number of rows and columns of the route map array, and we store them as `rows` and `cols`. Again, we do this to enable manipulation of a specific row/ column at a specific location. 

We first check if the current column is the last column of the route map. We do it because the goal of our algorithm is to navigate from the leftmost column to any location in the rightmost column. Hence, if y = cols - 1, it means that the algorithm has successfully reached the last column, which indicates a successful path has been found. Therefore, no need to continue, we just return the `route_map`. We add this check in the very beginning, because although it won't be used or relevant for the first execution of the code, it will be useful for the other executions, as our code includes recursion. This part of the code will disable recursion running forever. 

Then, we mark the current location on the route map as visited. Here, the  x and y refer to the current row and column of the location being processed. By setting `route_map[x, y]` to 1, we indicate that this position has been explored and is no longer available for further movement in the current search path. Then, we add the current location to the visited locations list. This list keeps track of all locations that have been visited during the current search path.

The next part of the code defines the potential directions our algorithm can move from the current location. We represent each move as a tuple containing: the new x-coordinate after the move (new_x), the new y-coordinate after the move (new_y), a direction code that indicates the type of movement. For example, `Move Right` means we stay at the same row x but move to the next column y + 1, and the direction code 40 indicates that the move is to the right. `Move Down` means we move down one row to x + 1 while staying in the same column y, and the direction code 20 indicates that the move is downward. `Move Left` means we stay in the same row x but move to the previous column y - 1, and the direction code 30 indicates that the move is to the left. Finally, `Move Up` means we move up one row to x - 1 while staying in the same column y, and the direction code 10 indicates that the move is upward.

We then iterate through each possible move. First, we check if the new position is valid. Meaning, if the new x-coordinate is within the range of valid rows and the new y-coordinate is within the range of valid columns. Then, we check ifhe new position is an empty space and if it has not been visited yet. If both of these conditions are trure, we found a new position! We mark it with it's corresponding direction code, to indicate how we arrived here (left, right, up, or down). 

Then, we use recursion to repeat all these on the new possible locations. Specifically, when we call the recursive function it tries to explore further paths from a new position. If that exploration leads to successfully reaching the last column of the route map, the function will return the updated route map with the path marked. If no valid path is found from the new position, find route will return None. Hence,
the line return result will be executed only if a valid route is found. We will then immediately return the successful path (the updated route map) back to the previous call in the recursion stack. 

However, if there is no possible route, then we reset the current location back to 1, to make it available for future moves. We also remove it from the visited locations list. By doing so, we allow other potential paths to explore it again in future searches. Finally, we return `None` as we could not find a valid route from the current location. 

In [10]:
def find_route(route_map, current_loc, visited_locs):
    """
    Recursively finds a route through the given route map from the current location.

    This function attempts to navigate from the current location to the last colum nof the route map. It marks the current location 
    as visited and explores possible moves (up, down, left, right) recursively. If a valid route is found, it returns the updated
    route map; otherwise, it backtracks by unmarking the current location.

    Args:
        route_map (numpy.ndarray): A 2D array representing the map, where:
            - 0 indicates a building.
            - 1 indicates an empty space.
            - 9 indicates a visited location.
            - Other values represent direction codes for movements (10 for up, 20 for down, 30 for left, 40 for right
        current_loc (tuple): A tuple (x, y) representing the current location on the map.
        visited_locs (list): A list of locations that have already been visited during the search.

    Returns:
        numpy.ndarray or None: 
            - Returns the updated route map if a route to the last column is found.
            - Returns None if no valid route exists from the current location.
    """
    x, y = current_loc
    rows, cols = route_map.shape
    
    # If we've reached the last column, return the route map
    if y == cols - 1:
        return route_map
    
    # We mark the current location with a unique direction code 9
    route_map[x, y] = 1  # Mark as visited
    visited_locs.append(current_loc)
    
    # We define possible moves: (new_x, new_y, code)
    moves = [
        (x - 1, y, 10),   # Move up
        (x + 1, y, 20),  # Move down
        (x, y - 1, 30),  # Move left
        (x, y + 1, 40),  # Move right
    ]
    
    for new_x, new_y, code in moves:
        # We check if the new position is valid
        if 0 <= new_x < rows and 0 <= new_y < cols:
            if route_map[new_x, new_y] == 1 and (new_x, new_y) not in visited_locs:
                # We mark the direction code for the move
                route_map[new_x, new_y] = code
                
                # We recursively try to find a route from the new position
                result = find_route(route_map, (new_x, new_y), visited_locs)
                
                # If a route is found, we return it
                if result is not None:
                    return result
    
    # If no route is found, we unmark the current location and backtrack
    route_map[x, y] = 1  # Unmark
    visited_locs.pop()  # Remove from visited list
    return None

In [11]:
# Now, let's test our function. We defined the output of the first function as route_map, and we will use it here.

# We start with an example location
current_loc = (0,9)

# We create an empty list to store the visited locations 
visited_locs = []

# We call the function
found = find_route(route_map, current_loc, visited_locs)
print(found)

[[ 1 -1  1  1  1  1  1  1  1  1]
 [-1  0 -1 -1  1  1  1  1  1  1]
 [ 1 -1 -1  0 -1  1  1  1  1  1]
 [ 1  1  1 -1  0 -1  1  1  1  1]
 [ 1  1  1  1 -1 -1  1  1  1  1]
 [ 1 -1  1  1 -1  0 -1  1 -1  1]
 [-1  0 -1  1  1 -1  1 -1  0 -1]
 [ 1 -1  1  1  1  1  1  1 -1  1]
 [-1  1  1  1  1 -1  1  1  1  1]
 [ 0 -1  1  1 -1  0 -1  1  1  1]
 [-1  1  1 -1  1 -1  1  1  1  1]
 [ 1  1 -1  0 -1  1  1  1  1  1]]


----------

Finally, for the last function, we create a dictionary called `symbols`. In this dictionary, we match the numbers with the corresponding meaningful symbols. Then, we iterate through each row of the route map. Then, we look up the value x in the dictionary. If the number exists as a key in symbol_map, it gives the corresponding symbol. If it does not exist in the dictionary, it defaults to returning the number itself. It repeats this for every number in the row. 

In [22]:
def pretty_printer(route_map):
    """
    Prints a visual representation of the route map using symbols.

    The function iterates through each row of the route_map and replaces numerical values with corresponding symbols 
    defined in the symbols dictionary for better visibility and understanding of the map's state.

    Args:
        route_map (list of list): A 2D list representing the map where each value corresponds to a specific type of location.
    """
    
    # We define a dictionary of numbers to symbols
    symbols = {
        1: '🛣️',   # Empty space
        0: '🏢',   # Building 
        -1: '❌',  # Parking spot
        10: '⬆️',  # Direction code for moving up
        20: '⬇️',  # Direction code for moving down
        30: '⬅️',  # Direction code for moving left
        40: '➡️'   # Direction code for moving right
    }

    # We iterate through each row in the route map
    for row in route_map:
        # We replace each value in the row with its corresponding symbol
        print([symbols.get(x, x) for x in row])

In [24]:
# Now, let's test our function.

final = pretty_printer(found)

['🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['❌', '🏢', '❌', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '❌', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '🛣️', '🛣️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '🛣️', '🛣️', '🛣️', '❌', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '❌', '🛣️', '🛣️', '❌', '🏢', '❌', '🛣️', '❌', '🛣️']
['❌', '🏢', '❌', '🛣️', '🛣️', '❌', '🛣️', '❌', '🏢', '❌']
['🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️', '❌', '🛣️']
['❌', '🛣️', '🛣️', '🛣️', '🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🏢', '❌', '🛣️', '🛣️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️']
['❌', '🛣️', '🛣️', '❌', '🛣️', '❌', '🛣️', '🛣️', '🛣️', '🛣️']
['🛣️', '🛣️', '❌', '🏢', '❌', '🛣️', '🛣️', '🛣️', '🛣️', '🛣️']
